apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Trino
    type: postgres
    url: trino:8080
    database: iceberg
    user: trino
    secureJsonData:
      password: ''
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1300
    editable: true
